server:
  port: 9090

spring:
  application:
    name: "gatewayserver"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: cuentas
          uri: lb://cuentas  # Nombre del servicio registrado en Eureka
          predicates:
            - Path=/cuentas/**
        - id: contactos
          uri: lb://contactos  # Nombre del servicio registrado en Eureka
          predicates:
            - Path=/contactos/**
        - id: movimientos
          uri: lb://movimientos  # Nombre del servicio registrado en Eureka
          predicates:
            - Path=/movimientos/**
        - id: transacciones
          uri: lb://transacciones  # Nombre del servicio registrado en Eureka
          predicates:
            - Path=/transacciones/**
        - id: usuarios
          uri: lb://usuarios  # Nombre del servicio registrado en Eureka
          predicates:
            - Path=/usuarios/**
        - id: whisper
          uri: lb://whisper  # Nombre del servicio registrado en Eureka
          predicates:
            - Path=/whisper/**

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "apigatewayserver"
    description: "Microservicio encargado de api gateway"
    version: "1.0.0"